volumes:
  legadilo_local_postgres_data: {}
  legadilo_local_postgres_data_backups: {}

services:
  django:
    build:
      pull: true
      context: .
      dockerfile: ./devops/compose/local/django/Dockerfile
    image: legadilo_local_django
    restart: unless-stopped
    container_name: legadilo_local_django
    depends_on:
      - postgres
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./devops/envs/local/postgres
      - ./devops/envs/local/django
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    build:
      pull: true
      context: .
      dockerfile: ./devops/compose/production/postgres/Dockerfile
    image: legadilo_production_postgres
    restart: unless-stopped
    container_name: legadilo_local_postgres
    volumes:
      - legadilo_local_postgres_data:/var/lib/postgresql/data
      - legadilo_local_postgres_data_backups:/backups
    env_file:
      - ./devops/envs/local/postgres
    ports:
      - "5432:5432"

  docs:
    image: legadilo_local_docs
    container_name: legadilo_local_docs
    build:
      context: .
      dockerfile: ./devops/compose/local/docs/Dockerfile
    env_file:
      - ./devops/envs/local/django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./legadilo:/app/legadilo:z
    ports:
      - "9000:9000"
    command: /start-docs.sh

  mailpit:
    image: axllent/mailpit:latest
    container_name: legadilo_local_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
