volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

services:
  django:
    build:
      pull: true
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: legadilo_production_django
    volumes:
      - production_django_media:/app/legadilo/media
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      pull: true
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: legadilo_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
