volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

services:
  django:
    build:
      pull: true
      context: .
      dockerfile: ./devops/compose/production/django/Dockerfile

    image: legadilo_production_django
    restart: unless-stopped
    volumes:
      - production_django_media:/app/legadilo/media
    depends_on:
      - postgres
    env_file:
      - ./devops/envs/production/django
      - ./devops/envs/production/postgres
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    build:
      pull: true
      context: .
      dockerfile: ./devops/compose/production/postgres/Dockerfile
    image: legadilo_production_postgres
    restart: unless-stopped
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./devops/envs/production/postgres
