# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

volumes:
  production_django_media: {}
  production_db_data: {}

services:
  legadilo:
    build:
      pull: true
      context: .
      dockerfile: ./devops/compose/production/django/Dockerfile
    image: legadilo_production_django
    restart: unless-stopped
    volumes:
      - production_django_media:/app/legadilo/media
      - production_db_data:/data
    env_file:
      - ./devops/envs/production/django
    environment:
      USE_DOCKER: "yes"
      DATABASE_URL: "sqlite:////data/legadilo.sqlite3"
      PYTHONUNBUFFERED: "1"
      IS_PRODUCTION: "true"
    ports:
      - "8000:8000"
    command:
      - /start.sh
      - server

  cron:
    image: legadilo_production_django
    restart: unless-stopped
    volumes:
      - production_db_data:/data
    depends_on:
      - legadilo
    env_file:
      - ./devops/envs/production/django
    environment:
      USE_DOCKER: "yes"
      DATABASE_URL: "sqlite:////data/legadilo.sqlite3"
      PYTHONUNBUFFERED: "1"
      IS_PRODUCTION: "true"
    command:
      # Wait for Django to start and for migrations to finish.
      - /start.sh
      - cron
