# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=config.settings.test --reuse-db"
python_files = [
    "tests.py",
    "test_*.py",
]

# ==== Coverage ====
[tool.coverage.run]
include = ["legado/**"]
omit = ["*/migrations/*", "*/tests/*"]
plugins = ["django_coverage_plugin"]


# ==== Ruf ====
[tool.ruff]
line-length = 119
target-version = "py312"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = [
    "legado",
    "config",
]


# ==== mypy ====
[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = [
    "mypy_django_plugin.main",
]

[[tool.mypy.overrides]]
# Django migrations should not produce any errors:
module = "*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "config.settings.test"


# ==== djLint ====
[tool.djlint]
blank_line_after_tag = "load,extends"
close_void_tags = true
format_css = true
format_js = true
# TODO: remove T002 when fixed https://github.com/Riverside-Healthcare/djLint/issues/687
ignore = "H006,H030,H031,T002"
include = "H017,H035"
indent = 4
max_line_length = 119
profile = "django"

[tool.djlint.css]
indent_size = 4

[tool.djlint.js]
indent_size = 4

[tool.poetry]
name = "legado"
version = "0.1.0"
description = ""
authors = ["Julien Enselme <jujens@jujens.eu>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

gunicorn = "21.2.0"  # https://github.com/benoitc/gunicorn
python-slugify = "8.0.1"  # https://github.com/un33k/python-slugify
Pillow = "10.1.0"  # https://github.com/python-pillow/Pillow
argon2-cffi = "23.1.0"  # https://github.com/hynek/argon2_cffi
whitenoise = "6.6.0"  # https://github.com/evansd/whitenoise
psycopg = { extras = ["binary"], version = "3.1.14" }  # https://github.com/psycopg/psycopg
uvicorn = { extras = ["standard"], version = "0.24.0.post1" } # https://github.com/encode/uvicorn

# Django
# ------------------------------------------------------------------------------
django = "4.2.8"  # pyup: < 5.0  # https://www.djangoproject.com/
django-environ = "0.11.2"  # https://github.com/joke2k/django-environ
django-allauth = "0.58.2"  # https://github.com/pennersr/django-allauth
django-crispy-forms = "2.1"  # https://github.com/django-crispy-forms/django-crispy-forms
crispy-bootstrap5 = "2023.10"  # https://github.com/django-crispy-forms/crispy-bootstrap5
django-anymail = "10.2"  # https://github.com/anymail/django-anymail

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pudb = "2023.1"  # https://documen.tician.de/pudb/
ipdb = "0.13.13"  # https://github.com/gotcha/ipdb

# Testing
# ------------------------------------------------------------------------------
mypy = "1.7.1"  # https://github.com/python/mypy
django-stubs = { extras = ["compatible-mypy"], version = "4.2.7" }  # https://github.com/typeddjango/django-stubs
pytest = "7.4.3"  # https://github.com/pytest-dev/pytest
pytest-sugar = "0.9.7"  # https://github.com/Frozenball/pytest-sugar
time-machine = "2.13.0"  #  https://github.com/adamchainz/time-machine

# Documentation
# ------------------------------------------------------------------------------
sphinx = "7.2.6"  # https://github.com/sphinx-doc/sphinx
sphinx-autobuild = "2021.3.14"  # https://github.com/GaretJax/sphinx-autobuild

# Code quality
# ------------------------------------------------------------------------------
coverage = "7.3.2"  # https://github.com/nedbat/coveragepy
ruff = "0.1.7"  # https://github.com/astral-sh/ruff
djlint = "1.34.0"  # https://github.com/Riverside-Healthcare/djLint
pre-commit = "3.5.0"  # https://github.com/pre-commit/pre-commit

# Django
# ------------------------------------------------------------------------------
factory-boy = "3.3.0"  # https://github.com/FactoryBoy/factory_boy
django-debug-toolbar = "4.2.0"  # https://github.com/jazzband/django-debug-toolbar
django-coverage-plugin = "3.1.0"  # https://github.com/nedbat/django_coverage_plugin
pytest-django = "4.7.0"  # https://github.com/pytest-dev/pytest-django


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
