# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.0 on 2023-12-11 22:03

from django.contrib.postgres.operations import CreateCollation
from django.db import connection, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    if connection.vendor == "postgresql":
        operations = [
            CreateCollation(
                "nocase",
                provider="icu",
                locale="und-u-ks-level2",
                deterministic=False,
            ),
        ]
    else:
        operations = []
