# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.1 on 2024-08-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_case_insensitive_collation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timezone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="timezone",
            constraint=models.UniqueConstraint(
                models.F("name"), name="core_timezone_unique_tz_name"
            ),
        ),
        migrations.AlterModelOptions(
            name="timezone",
            options={"ordering": ["name"]},
        ),
    ]
