# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.1 on 2024-08-10 10:25
from zoneinfo import available_timezones

from django.db import migrations, models


def fill_timezones(apps, schema_editor):
    Timezone = apps.get_model("core", "Timezone")
    timezones = []

    for tz in available_timezones():
        timezones.append(Timezone(name=tz))

    Timezone.objects.bulk_create(timezones)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_case_insensitive_collation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timezone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.RunPython(fill_timezones, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="timezone",
            constraint=models.UniqueConstraint(
                models.F("name"), name="core_timezone_unique_tz_name"
            ),
        ),
        migrations.AlterModelOptions(
            name="timezone",
            options={"ordering": ["name"]},
        ),
    ]
