# Generated by Django 6.0.1 on 2026-01-27 21:23

from django.contrib.postgres.operations import CreateCollation
from django.db import connection, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    if connection.vendor == "postgresql":
        operations = [
            CreateCollation(
                "nocase",
                provider="icu",
                locale="und-u-ks-level2",
                deterministic=False,
            ),
        ]
    else:
        operations = []
