# Generated by Django 6.0.1 on 2026-01-27 21:23

from django.contrib.postgres.operations import RemoveCollation
from django.db import connection, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_nocase_collation"),
        ("users", "0013_alter_user_email"),
    ]

    if connection.vendor == "postgresql":
        operations = [
            RemoveCollation(
                "case_insensitive",
                provider="icu",
                locale="und-u-ks-level2",
                deterministic=False,
            ),
        ]
    else:
        operations = []
