# Generated by Django 6.0.2 on 2026-02-22 19:26

import django.db.models.deletion
from django.db import migrations, models

import legadilo.core.utils.collections_utils
import legadilo.core.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleFetchError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                ("technical_debug_data", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArticlesGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ArticlesGroupTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "ordering": ("tag__title", "tag_id"),
            },
        ),
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "ordering": ["article_id", "tag__title", "tag_id"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ReadingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("enable_reading_on_scroll", models.BooleanField(default=False)),
                (
                    "auto_refresh_interval",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of hours after which to refresh reading lists automatically. 0 will disable the feature.",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "read_status",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("ONLY_UNREAD", "Only unread"),
                            ("ONLY_READ", "Only read"),
                        ],
                        default="ALL",
                        max_length=100,
                    ),
                ),
                (
                    "favorite_status",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("ONLY_FAVORITE", "Only favorite"),
                            ("ONLY_NON_FAVORITE", "Only non favorite"),
                        ],
                        default="ALL",
                        max_length=100,
                    ),
                ),
                (
                    "for_later_status",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("ONLY_FOR_LATER", "Only for later"),
                            ("ONLY_NOT_FOR_LATER", "Only for not later"),
                        ],
                        default="ALL",
                        max_length=100,
                    ),
                ),
                (
                    "articles_max_age_value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Articles published before today minus this number will be excluded from the reading list.",
                    ),
                ),
                (
                    "articles_max_age_unit",
                    models.CharField(
                        choices=[
                            ("UNSET", "Unset"),
                            ("HOURS", "Hour(s)"),
                            ("DAYS", "Day(s)"),
                            ("WEEKS", "Week(s)"),
                            ("MONTHS", "Month(s)"),
                        ],
                        default="UNSET",
                        help_text="Define the unit for the previous number. Leave to unset to not use this feature.",
                        max_length=100,
                    ),
                ),
                (
                    "articles_reading_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Include only articles that take more or less than this time to read.",
                    ),
                ),
                (
                    "articles_reading_time_operator",
                    models.CharField(
                        choices=[
                            ("UNSET", "Unset"),
                            ("MORE_THAN", "More than than"),
                            ("LESS_THAN", "Less than than"),
                        ],
                        default="UNSET",
                        help_text="Whether the reading time must be more or less that the supplied value.",
                        max_length=100,
                    ),
                ),
                (
                    "include_tag_operator",
                    models.CharField(
                        choices=[("ALL", "All"), ("ANY", "Any")],
                        default="ALL",
                        help_text="Defines whether the articles must have all or any of the tags to be included in the reading list.",
                        max_length=100,
                    ),
                ),
                (
                    "exclude_tag_operator",
                    models.CharField(
                        choices=[("ALL", "All"), ("ANY", "Any")],
                        default="ALL",
                        help_text="Defines whether the articles must have all or any of the tags to be excluded from the reading list.",
                        max_length=100,
                    ),
                ),
                (
                    "order_direction",
                    models.CharField(
                        choices=[("ASC", "Ascendant"), ("DESC", "Descendant")],
                        default="DESC",
                        help_text="How to sort the article. ASC will put the most recent articles first. DECS will put the least recent articles first.",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReadingListTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[("INCLUDE", "Include"), ("EXCLUDE", "Exclude")],
                        default="INCLUDE",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["tag__title", "tag_id"],
            },
        ),
        migrations.CreateModel(
            name="SubTagMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True)),
            ],
            options={
                "ordering": ["title", "id"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=300)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("application/xhtml+xml", "application/xhtml+xml"),
                            ("text/html", "text/html"),
                            ("text/plain", "text/plain"),
                        ],
                        default="text/html",
                        max_length=50,
                    ),
                ),
                (
                    "reading_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How much time in minutes is needed to read this article. If not specified, it will be calculated automatically from content length. If we don't have content, we will use 0.",
                    ),
                ),
                (
                    "authors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[legadilo.core.utils.validators.list_of_strings_validator],
                    ),
                ),
                (
                    "contributors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[legadilo.core.utils.validators.list_of_strings_validator],
                    ),
                ),
                ("url", models.URLField(max_length=1024)),
                ("preview_picture_url", models.URLField(blank=True, max_length=1024)),
                ("preview_picture_alt", models.TextField(blank=True)),
                (
                    "external_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags of the article from its source",
                        validators=[legadilo.core.utils.validators.list_of_strings_validator],
                    ),
                ),
                (
                    "external_article_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The id of the article in its source.",
                        max_length=512,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Annotations made to the article. Currently only used for data imports to prevent data loss.",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The language code for this article",
                        max_length=5,
                        validators=[legadilo.core.utils.validators.language_code_validator],
                    ),
                ),
                (
                    "table_of_content",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=legadilo.core.utils.collections_utils.CustomJsonEncoder,
                        help_text="The table of content of the article.",
                        validators=[legadilo.core.utils.validators.table_of_content_validator],
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_read",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(models.Q(("read_at__isnull", True)), then=False),
                            default=True,
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "was_opened",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(models.Q(("opened_at__isnull", True)), then=False),
                            default=True,
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("is_for_later", models.BooleanField(default=False)),
                (
                    "main_source_type",
                    models.CharField(
                        choices=[("FEED", "Feed"), ("MANUAL", "Manual")],
                        default="FEED",
                        max_length=100,
                    ),
                ),
                ("main_source_title", models.CharField(max_length=300)),
                (
                    "group_order",
                    models.PositiveIntegerField(default=0, help_text="Order in the group"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="The date of publication of the article.", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, help_text="The last time the article was updated.", null=True
                    ),
                ),
                (
                    "obj_created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Technical date for the creation of the article in the database.",
                    ),
                ),
                (
                    "obj_updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Technical date for the last update of the article in the database.",
                    ),
                ),
                (
                    "main_feed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles_main_feed",
                        to="feeds.feed",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-published_at", "id"],
            },
        ),
    ]
