# Generated by Django 6.0.2 on 2026-02-22 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("feeds", "0002_initial"),
        ("reading", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="articlefetcherror",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_fetch_errors",
                to="reading.article",
            ),
        ),
        migrations.AddField(
            model_name="articlesgroup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="reading.articlesgroup",
            ),
        ),
        migrations.AddField(
            model_name="articlesgrouptag",
            name="articles_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles_group_tags",
                to="reading.articlesgroup",
            ),
        ),
        migrations.AddField(
            model_name="articletag",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_tags",
                to="reading.article",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reading.article",
            ),
        ),
        migrations.AddField(
            model_name="readinglist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="readinglisttag",
            name="reading_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_list_tags",
                to="reading.readinglist",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="article_groups",
            field=models.ManyToManyField(
                related_name="tags", through="reading.ArticlesGroupTag", to="reading.articlesgroup"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="articles",
            field=models.ManyToManyField(
                related_name="tags", through="reading.ArticleTag", to="reading.article"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="feeds",
            field=models.ManyToManyField(
                related_name="tags", through="feeds.FeedTag", to="feeds.feed"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="reading_lists",
            field=models.ManyToManyField(
                related_name="tags", through="reading.ReadingListTag", to="reading.readinglist"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="sub_tags",
            field=models.ManyToManyField(
                related_name="base_tags", through="reading.SubTagMapping", to="reading.tag"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subtagmapping",
            name="base_tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_tag_mappings",
                to="reading.tag",
            ),
        ),
        migrations.AddField(
            model_name="subtagmapping",
            name="sub_tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_tag_mappings",
                to="reading.tag",
            ),
        ),
        migrations.AddField(
            model_name="readinglisttag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_list_tags",
                to="reading.tag",
            ),
        ),
        migrations.AddField(
            model_name="articletag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_tags",
                to="reading.tag",
            ),
        ),
        migrations.AddField(
            model_name="articlesgrouptag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles_group_tags",
                to="reading.tag",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["user", "is_read", "is_favorite", "is_for_later"],
                name="reading_art_user_id_ce8bcb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                models.F("user"), models.F("url"), name="reading_article_article_unique_for_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                condition=models.Q(("main_source_type__in", ["FEED", "MANUAL"])),
                name="reading_article_main_source_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "content_type__in",
                    ["application/xhtml+xml", "text/html", "text/plain"],
                )),
                name="reading_article_content_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                models.F("group"),
                models.F("group_order"),
                name="reading_article_group_order_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.UniqueConstraint(
                models.F("is_default"),
                models.F("user"),
                condition=models.Q(("is_default", True)),
                name="reading_readinglist_enforce_one_default_reading_list",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.UniqueConstraint(
                models.F("slug"), models.F("user"), name="reading_readinglist_enforce_slug_unicity"
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "articles_max_age_unit__in",
                    ["UNSET", "HOURS", "DAYS", "WEEKS", "MONTHS"],
                )),
                name="reading_readinglist_articles_max_age_unit_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "articles_reading_time_operator__in",
                    ["UNSET", "MORE_THAN", "LESS_THAN"],
                )),
                name="reading_readinglist_articles_reading_time_operator_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "favorite_status__in",
                    ["ALL", "ONLY_FAVORITE", "ONLY_NON_FAVORITE"],
                )),
                name="reading_readinglist_favorite_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                condition=models.Q(("read_status__in", ["ALL", "ONLY_UNREAD", "ONLY_READ"])),
                name="reading_readinglist_read_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "for_later_status__in",
                    ["ALL", "ONLY_FOR_LATER", "ONLY_NOT_FOR_LATER"],
                )),
                name="reading_readinglist_for_later_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                condition=models.Q(("exclude_tag_operator__in", ["ALL", "ANY"])),
                name="reading_readinglist_exclude_tag_operator_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                condition=models.Q(("include_tag_operator__in", ["ALL", "ANY"])),
                name="reading_readinglist_include_tag_operator_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                condition=models.Q(("order_direction__in", ["ASC", "DESC"])),
                name="reading_readinglist_order_direction_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                models.F("slug"), models.F("user_id"), name="reading_tag_tag_slug_unique_for_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="subtagmapping",
            constraint=models.UniqueConstraint(
                models.F("base_tag"),
                models.F("sub_tag"),
                name="reading_subtagmapping_unique_sub_tag_mapping_for_tag",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglisttag",
            constraint=models.UniqueConstraint(
                models.F("reading_list"),
                models.F("tag"),
                name="reading_readinglisttag_tagged_once_per_reading_list",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglisttag",
            constraint=models.CheckConstraint(
                condition=models.Q(("filter_type__in", ["INCLUDE", "EXCLUDE"])),
                name="reading_readinglisttag_filter_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="articletag",
            constraint=models.UniqueConstraint(
                models.F("article"),
                models.F("tag"),
                name="reading_articletag_tagged_once_per_article",
            ),
        ),
        migrations.AddConstraint(
            model_name="articlesgrouptag",
            constraint=models.UniqueConstraint(
                models.F("articles_group"),
                models.F("tag"),
                name="reading_articlesgrouptag_tagged_once_per_article_group",
            ),
        ),
    ]
