# Generated by Django 6.0.2 on 2026-02-22 19:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import connection, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("feeds", "0002_initial"),
        ("reading", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    if connection.vendor == "postgresql":
        operations = [
            migrations.AddIndex(
                model_name="article",
                index=django.contrib.postgres.indexes.GinIndex(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.CombinedSearchVector(
                                django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector(
                                        "title", config="english", weight="A"
                                    ),
                                    "||",
                                    django.contrib.postgres.search.SearchVector(
                                        "summary", config="english", weight="B"
                                    ),
                                    django.contrib.postgres.search.SearchConfig("english"),
                                ),
                                "||",
                                django.contrib.postgres.search.SearchVector(
                                    "content", config="english", weight="C"
                                ),
                                django.contrib.postgres.search.SearchConfig("english"),
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "authors", config="english", weight="C"
                            ),
                            django.contrib.postgres.search.SearchConfig("english"),
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "main_source_title", config="english", weight="D"
                        ),
                        django.contrib.postgres.search.SearchConfig("english"),
                    ),
                    name="reading_article_search_vector",
                ),
            ),
        ]
    else:
        operations = []
