# Generated by Django 5.0.6 on 2024-05-18 15:56

from django.db import migrations, models

import legadilo.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0002_article_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The language code for this article",
                max_length=5,
                validators=[legadilo.utils.validators.language_code_validator],
            ),
        ),
    ]
