# Generated by Django 6.0.3 on 2026-03-08 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0002_initial"),
        ("reading", "0003_article_reading_article_search_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="reading.articlesgroup",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="main_feed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles_main_feed",
                to="feeds.feed",
            ),
        ),
    ]
