# Legadilo
# Copyright (C) 2023-2025 by Legadilo contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-06-15 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0003_articlefetcherror_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="order_direction",
            field=models.CharField(
                choices=[("ASC", "Ascendant"), ("DESC", "Descendant")],
                default="DESC",
                help_text="How to sort the article. ASC will put the most recent articles first. DECS will put the least recent articles first.",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                condition=models.Q(("order_direction__in", ["ASC", "DESC"])),
                name="reading_readinglist_order_direction_valid",
            ),
        ),
    ]
