# Generated by Django 5.0.6 on 2024-05-18 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0003_article_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articletag",
            options={"ordering": ["article_id", "tag__title", "tag_id"]},
        ),
        migrations.AlterModelOptions(
            name="readinglisttag",
            options={"ordering": ["tag__title", "tag_id"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["title", "id"]},
        ),
        migrations.RenameField(
            model_name="readinglist",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="name",
            new_name="title",
        ),
    ]
