# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-06-15 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0003_articlefetcherror_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="order_direction",
            field=models.CharField(
                choices=[("ASC", "Ascendant"), ("DESC", "Descendant")],
                default="DESC",
                help_text="How to sort the article. ASC will put the most recent articles first. DECS will put the least recent articles first.",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                condition=models.Q(("order_direction__in", ["ASC", "DESC"])),
                name="reading_readinglist_order_direction_valid",
            ),
        ),
    ]
