# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-06-30 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0004_readinglist_order_direction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="article",
            name="reading_article_initial_source_type_valid",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="initial_source_title",
            new_name="main_source_title",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="initial_source_type",
            new_name="main_source_type",
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                condition=models.Q(("main_source_type__in", ["FEED", "MANUAL"])),
                name="reading_article_main_source_type_valid",
            ),
        ),
    ]
