# Generated by Django 5.0.6 on 2024-05-19 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0004_alter_articletag_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["user", "is_read", "is_favorite", "is_for_later"],
                name="reading_art_user_id_ce8bcb_idx",
            ),
        ),
    ]
