# Generated by Django 6.0.3 on 2026-03-17 20:28
from urllib.parse import urlparse

from django.db import migrations, models
from slugify import slugify

from legadilo.core.utils.pagination import paginate_qs


def fill_missing_slugs(apps, schema_editor):
    Article = apps.get_model("reading", "Article")
    for article in paginate_qs(
        Article.objects.filter(models.Q(slug="") | models.Q(title="")).order_by("id")
    ):
        fallback_title = urlparse(article.url).netloc
        article.title = article.title or fallback_title
        article.slug = slugify(article.title) or slugify(fallback_title)
        article.save(update_fields=["title", "slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0004_alter_article_group_alter_article_main_feed"),
    ]

    operations = [
        migrations.RunPython(fill_missing_slugs, reverse_code=migrations.RunPython.noop),
    ]
