# Generated by Django 5.0.6 on 2024-05-21 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0005_article_reading_art_user_id_ce8bcb_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-published_at", "id"]},
        ),
    ]
