# Generated by Django 5.0.6 on 2024-05-23 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0006_alter_article_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-updated_at", "-published_at", "id"]},
        ),
    ]
