# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.1.1 on 2024-09-08 20:46

from django.core.paginator import Paginator
from django.db import migrations, models

import legadilo.utils.validators
from legadilo.reading.services.article_fetching import _build_table_of_content


def build_toc(apps, schema):
    article_model = apps.get_model("reading", "Article")

    paginator = Paginator(article_model.objects.all(), 1_000)

    for page in paginator:
        for article in page:
            article.content, article.table_of_content = _build_table_of_content(article.content)
            article.save(update_fields=["content", "table_of_content"])


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0006_article_reading_article_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="table_of_content",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="The table of content of the article.",
                validators=[legadilo.utils.validators.table_of_content_validator],
            ),
        ),
        migrations.RunPython(build_toc, reverse_code=migrations.RunPython.noop),
    ]
