# Legadilo
# Copyright (C) 2023-2025 by Legadilo contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.1.1 on 2024-09-08 20:46

from django.core.paginator import Paginator
from django.db import migrations, models

import legadilo.utils.validators
from legadilo.reading.services.article_fetching import _build_table_of_content


def build_toc(apps, schema):
    article_model = apps.get_model("reading", "Article")

    paginator = Paginator(article_model.objects.all(), 1_000)

    for page in paginator:
        for article in page:
            article.content, article.table_of_content = _build_table_of_content(article.content)
            article.save(update_fields=["content", "table_of_content"])


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0006_article_reading_article_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="table_of_content",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="The table of content of the article.",
                validators=[legadilo.utils.validators.table_of_content_validator],
            ),
        ),
        migrations.RunPython(build_toc, reverse_code=migrations.RunPython.noop),
    ]
