# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.1.1 on 2024-10-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0007_article_table_of_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubTagMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "base_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_tag_mappings",
                        to="reading.tag",
                    ),
                ),
                (
                    "sub_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_tag_mappings",
                        to="reading.tag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tag",
            name="sub_tags",
            field=models.ManyToManyField(
                related_name="base_tags", through="reading.SubTagMapping", to="reading.tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="subtagmapping",
            constraint=models.UniqueConstraint(
                models.F("base_tag"),
                models.F("sub_tag"),
                name="reading_subtagmapping_unique_sub_tag_mapping_for_tag",
            ),
        ),
    ]
