# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.1.3 on 2024-11-23 16:49

from django.db import migrations, models

import legadilo.utils.collections_utils
import legadilo.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0009_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="table_of_content",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=legadilo.utils.collections_utils.CustomJsonEncoder,
                help_text="The table of content of the article.",
                validators=[legadilo.utils.validators.table_of_content_validator],
            ),
        ),
    ]
