# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2 on 2025-04-08 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0010_alter_article_table_of_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="article",
            name="reading_article_article_unique_for_user",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="link",
            new_name="url",
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                models.F("user"), models.F("url"), name="reading_article_article_unique_for_user"
            ),
        ),
    ]
