# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.2 on 2025-06-07 14:04

from django.db import migrations, models
from django.db.models.functions import Ceil


def convert_auto_refresh_interval_to_hours(apps, schema_editor):
    ReadingList = apps.get_model("reading", "ReadingList")

    ReadingList.objects.filter(auto_refresh_interval__gt=0).update(
        auto_refresh_interval=Ceil(models.F("auto_refresh_interval") / 3600),
    )


def convert_auto_refresh_interval_to_seconds(apps, schema_editor):
    ReadingList = apps.get_model("reading", "ReadingList")

    ReadingList.objects.filter(auto_refresh_interval__gt=0).update(
        auto_refresh_interval=models.F("auto_refresh_interval") * 3600,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0011_remove_article_reading_article_article_unique_for_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readinglist",
            name="auto_refresh_interval",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of hours after which to refresh reading lists automatically. 0 will disable the feature.",
            ),
        ),
        migrations.RunPython(
            convert_auto_refresh_interval_to_hours,
            reverse_code=convert_auto_refresh_interval_to_seconds,
        ),
    ]
