# Legadilo
# Copyright (C) 2023-2025 by Legadilo contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.2 on 2025-06-07 14:04

from django.db import migrations, models
from django.db.models.functions import Ceil


def convert_auto_refresh_interval_to_hours(apps, schema_editor):
    ReadingList = apps.get_model("reading", "ReadingList")

    ReadingList.objects.filter(auto_refresh_interval__gt=0).update(
        auto_refresh_interval=Ceil(models.F("auto_refresh_interval") / 3600),
    )


def convert_auto_refresh_interval_to_seconds(apps, schema_editor):
    ReadingList = apps.get_model("reading", "ReadingList")

    ReadingList.objects.filter(auto_refresh_interval__gt=0).update(
        auto_refresh_interval=models.F("auto_refresh_interval") * 3600,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0011_remove_article_reading_article_article_unique_for_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readinglist",
            name="auto_refresh_interval",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of hours after which to refresh reading lists automatically. 0 will disable the feature.",
            ),
        ),
        migrations.RunPython(
            convert_auto_refresh_interval_to_hours,
            reverse_code=convert_auto_refresh_interval_to_seconds,
        ),
    ]
