# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.4 on 2025-07-27 09:18
import html

from django.db import migrations

from legadilo.utils.pagination import paginate_qs
from legadilo.utils.security import full_sanitize, sanitize_keep_safe_tags


def apply_cleaner_sanitization(apps, schema_editor):
    Article = apps.get_model("reading", "Article")
    for article in paginate_qs(Article.objects.all()):
        article.title = _clean_field(article.title)
        article.save(update_fields=["title"])

    Tag = apps.get_model("reading", "Tag")
    for tag in Tag.objects.all():
        tag.title = _clean_field(tag.title)
        tag.save(update_fields=["title"])

    Comment = apps.get_model("reading", "Comment")
    for comment in Comment.objects.all():
        comment.text = html.unescape(comment.text)
        comment.text = sanitize_keep_safe_tags(comment.text)
        comment.save(update_fields=["text"])

    ReadingList = apps.get_model("reading", "ReadingList")
    for reading_list in ReadingList.objects.all():
        reading_list.title = _clean_field(reading_list.title)
        reading_list.save(update_fields=["title"])


def _clean_field(field_value):
    unescaped = html.unescape(field_value)
    return full_sanitize(unescaped)


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0012_alter_readinglist_auto_refresh_interval"),
    ]

    operations = [
        migrations.RunPython(apply_cleaner_sanitization, reverse_code=migrations.RunPython.noop),
    ]
