# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.7 on 2025-10-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0013_apply_cleaner_sanitization"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("application/xhtml+xml", "application/xhtml+xml"),
                    ("text/html", "text/html"),
                    ("text/plain", "text/plain"),
                ],
                default="text/html",
                max_length=50,
            ),
        ),
    ]
