# Generated by Django 6.0 on 2025-12-05 21:53

import django.db.models.deletion
from django.contrib.postgres.aggregates import ArrayAgg
from django.db import migrations, models

from legadilo.core.utils.pagination import paginate_qs


def set_main_feed(apps, schema_editor):
    Article = apps.get_model("reading", "Article")
    for article in paginate_qs(
        Article.objects
        .annotate(
            feed_ids=ArrayAgg(
                "feed_articles__feed_id",
                order_by=("feed_articles__created_at", "feed_articles__feed_id"),
            )
        )
        .order_by("id")
        .all()
    ):
        article.main_feed_id = article.feed_ids[0]
        article.save(update_fields=["main_feed_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0014_rename_ignored_article_urls_feedupdate_ignored_article_ids_and_more"),
        ("reading", "0015_article_reading_article_content_type_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="main_feed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles_main_feed",
                to="feeds.feed",
            ),
        ),
        migrations.RunPython(set_main_feed, reverse_code=migrations.RunPython.noop),
    ]
