# Generated by Django 6.0 on 2025-12-09 22:11

from django.db import migrations


def delete_deleted_tags(apps, schema_editor):
    ArticleTag = apps.get_model("reading", "ArticleTag")
    ArticleTag.objects.filter(tagging_reason="DELETED").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0016_article_main_feed_id"),
    ]

    operations = [
        migrations.RunPython(delete_deleted_tags, reverse_code=migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="articletag",
            name="reading_articletag_tagging_reason_valid",
        ),
        migrations.RemoveField(
            model_name="articletag",
            name="tagging_reason",
        ),
    ]
