# Generated by Django 6.0 on 2025-12-14 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0017_remove_articletag_reading_articletag_tagging_reason_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="group_order",
            field=models.PositiveIntegerField(default=0, help_text="Order in the group"),
        ),
        migrations.CreateModel(
            name="ArticlesGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="article",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="reading.articlesgroup",
            ),
        ),
        migrations.CreateModel(
            name="ArticlesGroupTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "article_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_group_tags",
                        to="reading.articlesgroup",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_group_tags",
                        to="reading.tag",
                    ),
                ),
            ],
            options={
                "ordering": ("tag__title", "tag_id"),
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="article_groups",
            field=models.ManyToManyField(
                related_name="tags", through="reading.ArticlesGroupTag", to="reading.articlesgroup"
            ),
        ),
        migrations.AddConstraint(
            model_name="articlesgrouptag",
            constraint=models.UniqueConstraint(
                models.F("article_group"),
                models.F("tag"),
                name="reading_articlesgrouptag_tagged_once_per_article_group",
            ),
        ),
    ]
