# Generated by Django 6.0 on 2025-12-14 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0014_rename_ignored_article_urls_feedupdate_ignored_article_ids_and_more"),
        ("reading", "0018_article_group_order_articlesgroup_article_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                models.F("group"),
                models.F("group_order"),
                name="reading_article_group_order_unique",
            ),
        ),
    ]
