# Generated by Django 6.0 on 2025-12-22 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0019_article_reading_article_group_order_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="articlesgrouptag",
            name="reading_articlesgrouptag_tagged_once_per_article_group",
        ),
        migrations.RenameField(
            model_name="articlesgrouptag",
            old_name="article_group",
            new_name="articles_group",
        ),
        migrations.AlterField(
            model_name="articlesgrouptag",
            name="articles_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles_group_tags",
                to="reading.articlesgroup",
            ),
        ),
        migrations.AlterField(
            model_name="articlesgrouptag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles_group_tags",
                to="reading.tag",
            ),
        ),
        migrations.AddConstraint(
            model_name="articlesgrouptag",
            constraint=models.UniqueConstraint(
                models.F("articles_group"),
                models.F("tag"),
                name="reading_articlesgrouptag_tagged_once_per_article_group",
            ),
        ),
    ]
