# Generated by Django 6.0.2 on 2026-02-22 19:26

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import legadilo.core.utils.db
import legadilo.users.models.user


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Username")),
                (
                    "email",
                    legadilo.core.utils.db.CaseInsensitiveEmailField(
                        db_collation="nocase",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", legadilo.users.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "session_key",
                    models.CharField(
                        max_length=40, primary_key=True, serialize=False, verbose_name="session key"
                    ),
                ),
                ("session_data", models.TextField(verbose_name="session data")),
                ("expire_date", models.DateTimeField(db_index=True, verbose_name="expire date")),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApplicationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "title",
                    models.CharField(
                        help_text="Give the token a nice name to identify its usage more easily.",
                        max_length=255,
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                (
                    "validity_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty to have a token that will last until deletion.",
                        null=True,
                        verbose_name="Validity end",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this token was last used to create an access token.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("token",), name="users_applicationtoken_token_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("uuid",), name="users_applicationtoken_uuid_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("title", "user"), name="users_applicationtoken_title_user_unique"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True)),
                ("info_link", models.URLField(blank=True)),
                ("info_link_text", models.CharField(blank=True, max_length=100)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_read",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(read_at__isnull=True, then=False), default=True
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("info_link__length", 0), ("info_link_text__length", 0)),
                            models.Q(
                                ("info_link__length__gt", 0), ("info_link_text__length__gt", 0)
                            ),
                            _connector="OR",
                        ),
                        name="users_notification_info_link_and_info_link_text_set_together",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "default_reading_time",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="Number of words you read in minutes. Used to calculate the reading time of articles.",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("", ""), ("en", "English"), ("fr", "French")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.ForeignKey(
                        help_text="Used to display times and updated feeds at a convenient time.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_settings",
                        to="core.timezone",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        models.F("user"), name="users_usersettings_unique_per_user"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("language__in", ["", "en", "fr"])),
                        name="users_usersettings_language_valid",
                    ),
                ],
            },
        ),
    ]
