# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.1 on 2024-08-10 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("users", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="timezone",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_settings",
                to="core.timezone",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="timezone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_settings",
                to="core.timezone",
                help_text="Used to display times and updated feeds at a convenient time.",
            ),
        ),
    ]
