# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.1 on 2024-08-10 10:30

import django.db.models.deletion
from django.db import migrations, models


def set_default_tz(apps, schema_editor):
    UserSettings = apps.get_model("users", "UserSettings")
    Timezone = apps.get_model("core", "Timezone")
    utc_tz = Timezone.objects.get(name="UTC")

    UserSettings.objects.filter(timezone__isnull=True).update(timezone=utc_tz)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("users", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="timezone",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_settings",
                to="core.timezone",
            ),
        ),
        migrations.RunPython(set_default_tz, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="usersettings",
            name="timezone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_settings",
                to="core.timezone",
                help_text="Used to display times and updated feeds at a convenient time.",
            ),
        ),
    ]
