# Legadilo
# Copyright (C) 2023-2024 by Legadilo contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.1 on 2024-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_usersettings_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="link_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("link__length", 0), ("link_text__length", 0)),
                    models.Q(("link__length__gt", 0), ("link_text__length__gt", 0)),
                    _connector="OR",
                ),
                name="users_notification_link_and_text_set_together",
            ),
        ),
    ]
