# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.1 on 2024-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_usersettings_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="link_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("link__length", 0), ("link_text__length", 0)),
                    models.Q(("link__length__gt", 0), ("link_text__length__gt", 0)),
                    _connector="OR",
                ),
                name="users_notification_link_and_text_set_together",
            ),
        ),
    ]
