# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.1.3 on 2024-12-01 14:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_applicationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtoken",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="applicationtoken",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this token was last used to create an access token.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="applicationtoken",
            name="title",
            field=models.CharField(
                help_text="Give the token a nice name to identify its usage more easily.",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationtoken",
            constraint=models.UniqueConstraint(
                fields=("uuid",), name="users_applicationtoken_uuid_unique"
            ),
        ),
    ]
