# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2 on 2025-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_applicationtoken_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="users_notification_link_and_text_set_together",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="link",
            new_name="url",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="link_text",
            new_name="url_text",
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("url__length", 0), ("url_text__length", 0)),
                    models.Q(("url__length__gt", 0), ("url_text__length__gt", 0)),
                    _connector="OR",
                ),
                name="users_notification_url_and_text_set_together",
            ),
        ),
    ]
