# Legadilo
# Copyright (C) 2023-2025 by Legadilo contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.2 on 2025-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_applicationtoken_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="users_notification_link_and_text_set_together",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="link",
            new_name="url",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="link_text",
            new_name="url_text",
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("url__length", 0), ("url_text__length", 0)),
                    models.Q(("url__length__gt", 0), ("url_text__length__gt", 0)),
                    _connector="OR",
                ),
                name="users_notification_url_and_text_set_together",
            ),
        ),
    ]
