# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2 on 2025-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0008_remove_notification_users_notification_link_and_text_set_together_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="users_notification_url_and_text_set_together",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="url",
            new_name="info_link",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="url_text",
            new_name="info_link_text",
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("info_link__length", 0), ("info_link_text__length", 0)),
                    models.Q(("info_link__length__gt", 0), ("info_link_text__length__gt", 0)),
                    _connector="OR",
                ),
                name="users_notification_info_link_and_info_link_text_set_together",
            ),
        ),
    ]
