# Generated by Django 6.0.1 on 2026-01-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_notification_users_notification_url_and_text_set_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Username"),
        ),
    ]
