# Generated by Django 6.0.1 on 2026-01-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("users", "0011_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("en", "English"), ("fr", "French")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("language__in", ["", "en", "fr"])),
                name="users_usersettings_language_valid",
            ),
        ),
    ]
