# Generated by Django 6.0.2 on 2026-02-22 16:00

from django.db import migrations

import legadilo.core.utils.db


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_nocase_collation"),
        ("users", "0012_usersettings_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=legadilo.core.utils.db.CaseInsensitiveEmailField(
                db_collation="nocase", max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
