# Legadilo
# Copyright (C) 2023-2025 by Legadilo contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-05-23 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeedCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="FeedTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "ordering": ["tag__title", "tag_id"],
            },
        ),
        migrations.CreateModel(
            name="FeedUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("NOT_MODIFIED", "Not Modified"),
                        ],
                        max_length=100,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("feed_etag", models.CharField(max_length=100)),
                ("feed_last_modified", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("feed_url", models.URLField()),
                ("site_url", models.URLField()),
                ("enabled", models.BooleanField(default=True)),
                ("disabled_reason", models.TextField(blank=True)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "feed_type",
                    models.CharField(
                        choices=[
                            ("rss090", "RSS 0.90"),
                            ("rss091n", "RSS 0.91 (Netscape)"),
                            ("rss091u", "RSS 0.91 (Userland)"),
                            ("rss092", "RSS 0.92"),
                            ("rss093", "RSS 0.93"),
                            ("rss094", "RSS 0.94"),
                            ("rss20", "RSS 2.0"),
                            ("rss10", "RSS 1.0"),
                            ("rss", "RSS (unknown version)"),
                            ("atom01", "Atom 0.1"),
                            ("atom02", "Atom 0.2"),
                            ("atom03", "Atom 0.3"),
                            ("atom10", "Atom 1.0"),
                            ("atom", "Atom (unknown version)"),
                            ("cdf", "CDF"),
                            ("json1", "JSON 1"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "refresh_delay",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("BIHOURLY", "Bihourly"),
                            ("EVERY_MORNING", "Every Morning"),
                            ("DAILY_AT_NOON", "Daily at Noon"),
                            ("EVERY_EVENING", "Every Evening"),
                            ("ON_MONDAYS", "On Mondays"),
                            ("ON_THURSDAYS", "On Thursdays"),
                            ("TWICE_A_WEEK", "Twice a week"),
                            ("FIRST_DAY_OF_THE_MONTH", "First Day of the Month"),
                            ("MIDDLE_OF_THE_MONTH", "Middle Day of the Month"),
                            ("END_OF_THE_MONTH", "End of the Month"),
                            ("THRICE_A_MONTH", "Thrice a month"),
                        ],
                        default="DAILY_AT_NOON",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
