# Generated by Django 5.0 on 2023-12-28 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("feed_url", models.URLField()),
                ("site_url", models.URLField()),
                ("enabled", models.BooleanField(default=True)),
                ("title", models.CharField()),
                ("description", models.TextField()),
                (
                    "feed_type",
                    models.CharField(
                        choices=[
                            ("rss090", "RSS 0.90"),
                            ("rss091n", "RSS 0.91 (Netscape)"),
                            ("rss091u", "RSS 0.91 (Userland)"),
                            ("rss092", "RSS 0.92"),
                            ("rss093", "RSS 0.93"),
                            ("rss094", "RSS 0.94"),
                            ("rss20", "RSS 2.0"),
                            ("rss10", "RSS 1.0"),
                            ("rss", "RSS (unknown version)"),
                            ("atom01", "Atom 0.1"),
                            ("atom02", "Atom 0.2"),
                            ("atom03", "Atom 0.3"),
                            ("atom10", "Atom 1.0"),
                            ("atom", "Atom (unknown version)"),
                            ("cdf", "CDF"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.UniqueConstraint(
                models.F("feed_url"), models.F("user"), name="feeds_Feed_feed_url_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                check=models.Q((
                    "feed_type__in",
                    [
                        "rss090",
                        "rss091n",
                        "rss091u",
                        "rss092",
                        "rss093",
                        "rss094",
                        "rss20",
                        "rss10",
                        "rss",
                        "atom01",
                        "atom02",
                        "atom03",
                        "atom10",
                        "atom",
                        "cdf",
                    ],
                )),
                name="feeds_Feed_feed_type_valid",
            ),
        ),
    ]
