# Generated by Django 6.0.2 on 2026-02-22 19:26

from django.db import migrations, models

import legadilo.core.utils.time_utils
import legadilo.core.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("feed_url", models.URLField()),
                ("site_url", models.URLField()),
                (
                    "enabled",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(models.Q(("disabled_at__isnull", True)), then=True),
                            default=False,
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                ("disabled_reason", models.TextField(blank=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "feed_type",
                    models.CharField(
                        choices=[
                            ("rss090", "RSS 0.90"),
                            ("rss091n", "RSS 0.91 (Netscape)"),
                            ("rss091u", "RSS 0.91 (Userland)"),
                            ("rss092", "RSS 0.92"),
                            ("rss093", "RSS 0.93"),
                            ("rss094", "RSS 0.94"),
                            ("rss20", "RSS 2.0"),
                            ("rss10", "RSS 1.0"),
                            ("rss", "RSS (unknown version)"),
                            ("atom01", "Atom 0.1"),
                            ("atom02", "Atom 0.2"),
                            ("atom03", "Atom 0.3"),
                            ("atom10", "Atom 1.0"),
                            ("atom", "Atom (unknown version)"),
                            ("cdf", "CDF"),
                            ("json1", "JSON 1"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "refresh_delay",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("BIHOURLY", "Bihourly"),
                            ("EVERY_MORNING", "Every Morning"),
                            ("DAILY_AT_NOON", "Daily at Noon"),
                            ("EVERY_EVENING", "Every Evening"),
                            ("ON_MONDAYS", "On Mondays"),
                            ("ON_THURSDAYS", "On Thursdays"),
                            ("ON_SATURDAYS", "On Saturdays"),
                            ("ON_SUNDAYS", "On Sundays"),
                            ("TWICE_A_WEEK", "Twice a week"),
                            ("FIRST_DAY_OF_THE_MONTH", "First Day of the Month"),
                            ("MIDDLE_OF_THE_MONTH", "Middle Day of the Month"),
                            ("END_OF_THE_MONTH", "End of the Month"),
                            ("THRICE_A_MONTH", "Thrice a month"),
                        ],
                        default="DAILY_AT_NOON",
                        max_length=100,
                    ),
                ),
                (
                    "article_retention_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Define for how long in days to keep read articles associated with this feed. Use 0 to always keep the articles.",
                    ),
                ),
                ("open_original_url_by_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="FeedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("feed_article_id", models.TextField()),
                (
                    "last_seen_at",
                    models.DateTimeField(default=legadilo.core.utils.time_utils.utcnow),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeedCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="FeedTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "ordering": ["tag__title", "tag_id"],
            },
        ),
        migrations.CreateModel(
            name="FeedUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("NOT_MODIFIED", "Not Modified"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "ignored_article_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[legadilo.core.utils.validators.list_of_strings_validator],
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("technical_debug_data", models.JSONField(blank=True, null=True)),
                ("feed_etag", models.CharField(max_length=100)),
                ("feed_last_modified", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
