# Generated by Django 5.0 on 2023-12-30 12:31

import django.db.models.deletion
from django.db import migrations, models

import legadilo.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField()),
                ("summary", models.TextField()),
                ("content", models.TextField()),
                (
                    "authors",
                    models.JSONField(
                        validators=[
                            legadilo.utils.validators.JsonSchemaValidator({
                                "items": {"type": "string"},
                                "type": "array",
                            })
                        ]
                    ),
                ),
                (
                    "contributors",
                    models.JSONField(
                        validators=[
                            legadilo.utils.validators.JsonSchemaValidator({
                                "items": {"type": "string"},
                                "type": "array",
                            })
                        ]
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        validators=[
                            legadilo.utils.validators.JsonSchemaValidator({
                                "items": {"type": "string"},
                                "type": "array",
                            })
                        ]
                    ),
                ),
                ("link", models.URLField()),
                ("published_at", models.DateTimeField()),
                (
                    "article_feed_id",
                    models.CharField(help_text="The id of the article in the feed."),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="feeds.feed",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                models.F("article_feed_id"),
                models.F("feed_id"),
                name="feeds_Article_article_unique_in_feed",
            ),
        ),
    ]
