# Generated by Django 5.0 on 2023-12-31 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0002_article_article_feeds_article_article_unique_in_feed"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("success", models.BooleanField()),
                ("error_message", models.TextField(blank=True)),
                ("feed_etag", models.CharField()),
                ("feed_last_modified", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="feed_updates", to="feeds.feed"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
