# Generated by Django 6.0.3 on 2026-03-17 19:56
from urllib.parse import urlparse

from django.db import migrations, models
from slugify import slugify

from legadilo.core.utils.pagination import paginate_qs


def fill_missing_slugs(apps, schema_editor):
    Feed = apps.get_model("feeds", "Feed")
    for feed in paginate_qs(
        Feed.objects.filter(models.Q(slug="") | models.Q(title="")).order_by("id")
    ):
        fallback_title = urlparse(feed.feed_url).netloc
        feed.title = feed.title or fallback_title
        feed.slug = slugify(feed.title) or slugify(fallback_title)
        feed.save(update_fields=["title", "slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(fill_missing_slugs, reverse_code=migrations.RunPython.noop),
    ]
