# Generated by Django 5.0.6 on 2024-05-18 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedcategory",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="feedtag",
            options={"ordering": ["tag__title", "tag_id"]},
        ),
        migrations.RenameField(
            model_name="feedcategory",
            old_name="name",
            new_name="title",
        ),
    ]
