# Generated by Django 5.0.6 on 2024-05-20 20:13

from django.db import migrations, models
from slugify import slugify


def fill_feed_slug(apps, schema_editor):
    feed_model = apps.get_model("feeds", "Feed")

    for feed in feed_model.objects.all():
        feed.slug = slugify(feed.title)
        feed.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0003_alter_feedcategory_options_alter_feedtag_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="slug",
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.RunPython(fill_feed_slug, reverse_code=migrations.RunPython.noop),
    ]
