# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-05-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0003_remove_feed_feeds_feed_disabled_reason_empty_when_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedupdate",
            name="technical_debug_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
