# Generated by Django 5.0.3 on 2024-03-17 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0004_feed_disabled_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feed",
            name="feeds_Feed_feed_type_valid",
        ),
        migrations.RemoveConstraint(
            model_name="feed",
            name="feeds_Feed_disabled_reason_empty_when_enabled",
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                check=models.Q((
                    "feed_type__in",
                    [
                        "rss090",
                        "rss091n",
                        "rss091u",
                        "rss092",
                        "rss093",
                        "rss094",
                        "rss20",
                        "rss10",
                        "rss",
                        "atom01",
                        "atom02",
                        "atom03",
                        "atom10",
                        "atom",
                        "cdf",
                    ],
                )),
                name="feeds_feed_feed_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("disabled_reason", ""), ("enabled", True)),
                    ("enabled", False),
                    _connector="OR",
                ),
                name="feeds_feed_disabled_reason_empty_when_enabled",
            ),
        ),
    ]
