# Generated by Django 5.0.6 on 2024-06-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0004_feedupdate_technical_debug_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="open_original_link_by_default",
            field=models.BooleanField(default=False),
        ),
    ]
