# Legadilo
# Copyright (C) 2023-2025 by Legadilo contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-06-30 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0005_feed_open_original_link_by_default"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="feedcategory",
            old_name="modified_at",
            new_name="updated_at",
        ),
    ]
