# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-06-30 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0005_feed_open_original_link_by_default"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="feedcategory",
            old_name="modified_at",
            new_name="updated_at",
        ),
    ]
