# Generated by Django 5.0.3 on 2024-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0005_remove_feed_feeds_feed_feed_type_valid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="article",
            name="feeds_Article_article_unique_in_feed",
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                models.F("article_feed_id"),
                models.F("feed_id"),
                name="feeds_article_article_unique_in_feed",
            ),
        ),
    ]
