# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-07-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0006_rename_modified_at_feed_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="feed", name="enabled"),
        migrations.AddField(
            model_name="feed",
            name="enabled",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(models.Q(("disabled_at__isnull", True)), then=True), default=False
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
