# Generated by Django 5.0.3 on 2024-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0006_remove_article_feeds_article_article_unique_in_feed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="was_opened",
            field=models.BooleanField(default=False),
        ),
    ]
