# Legadilo
# Copyright (C) 2023-2025 by Legadilo contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.0.6 on 2024-07-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0006_rename_modified_at_feed_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="feed", name="enabled"),
        migrations.AddField(
            model_name="feed",
            name="enabled",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(models.Q(("disabled_at__isnull", True)), then=True), default=False
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
