# Generated by Django 5.0.3 on 2024-03-17 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0007_article_is_favorite_article_was_opened"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("is_default", models.BooleanField(default=False)),
                (
                    "read_status",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("ONLY_UNREAD", "Only unread"),
                            ("ONLY_READ", "Only read"),
                        ],
                        default="ALL",
                    ),
                ),
                (
                    "favorite_status",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("ONLY_FAVORITE", "Only favorite"),
                            ("ONLY_NON_FAVORITE", "Only non favorite"),
                        ],
                        default="ALL",
                    ),
                ),
                (
                    "articles_max_age_value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Articles published before today minus this number will be excluded from the reading list.",
                    ),
                ),
                (
                    "articles_max_age_unit",
                    models.CharField(
                        choices=[
                            ("UNSET", "Unset"),
                            ("HOURS", "Hour(s)"),
                            ("DAYS", "Day(s)"),
                            ("WEEKS", "Week(s)"),
                            ("MONTHS", "Month(s)"),
                        ],
                        default="UNSET",
                        help_text="Define the unit for the previous number. Leave to unset to not use this feature.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.UniqueConstraint(
                models.F("is_default"),
                models.F("user"),
                condition=models.Q(("is_default", True)),
                name="feeds_readinglist_enforce_one_default_reading_list",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                check=models.Q((
                    "articles_max_age_unit__in",
                    ["UNSET", "HOURS", "DAYS", "WEEKS", "MONTHS"],
                )),
                name="feeds_readinglist_articles_max_age_unit_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                check=models.Q((
                    "favorite_status__in",
                    ["ALL", "ONLY_FAVORITE", "ONLY_NON_FAVORITE"],
                )),
                name="feeds_readinglist_favorite_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                check=models.Q(("read_status__in", ["ALL", "ONLY_UNREAD", "ONLY_READ"])),
                name="feeds_readinglist_read_status_valid",
            ),
        ),
    ]
