# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.1.1 on 2024-09-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0007_alter_feed_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="article_retention_time",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Define for how long in days to keep read articles associated with this feed. Use 0 to always keep the articles.",
            ),
        ),
    ]
