# Legadilo
# Copyright (C) 2023-2025 by Legadilo contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.1.1 on 2024-09-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0007_alter_feed_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="article_retention_time",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Define for how long in days to keep read articles associated with this feed. Use 0 to always keep the articles.",
            ),
        ),
    ]
