# Legadilo
# Copyright (C) 2023-2024 by Legadilo contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.1.2 on 2024-10-12 16:04

import django.db.models.deletion
from django.db import migrations, models

import legadilo.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0008_feed_article_retention_time"),
        ("reading", "0007_article_table_of_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedupdate",
            name="ignored_article_links",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[legadilo.utils.validators.list_of_strings_json_schema_validator],
            ),
        ),
        migrations.AlterField(
            model_name="feedarticle",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feed_articles",
                to="reading.article",
            ),
        ),
        migrations.CreateModel(
            name="FeedDeletedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("article_link", models.URLField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deleted_articles",
                        to="feeds.feed",
                    ),
                ),
            ],
            options={
                "db_table_comment": "Maintain a list of deleted article links from a feed so we don't add it again on next update.",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("article_link"),
                        models.F("feed"),
                        name="feeds_feeddeletedarticle_delete_article_once_per_feed",
                    )
                ],
            },
        ),
    ]
