# Generated by Django 5.0.3 on 2024-03-19 21:21

from django.db import migrations, models

import legadilo.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0009_readinglist_feeds_readinglist_enforce_slug_unicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="authors",
            field=models.JSONField(
                blank=True,
                validators=[
                    legadilo.utils.validators.JsonSchemaValidator({
                        "items": {"type": "string"},
                        "type": "array",
                    })
                ],
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="contributors",
            field=models.JSONField(
                blank=True,
                validators=[
                    legadilo.utils.validators.JsonSchemaValidator({
                        "items": {"type": "string"},
                        "type": "array",
                    })
                ],
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.JSONField(
                blank=True,
                validators=[
                    legadilo.utils.validators.JsonSchemaValidator({
                        "items": {"type": "string"},
                        "type": "array",
                    })
                ],
            ),
        ),
    ]
