# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.1.2 on 2024-10-19 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0009_feedupdate_ignored_article_links_and_more"),
        ("reading", "0008_subtagmapping_tag_sub_tags_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feed",
            name="feeds_feed_refresh_delay_type_valid",
        ),
        migrations.AlterField(
            model_name="feed",
            name="refresh_delay",
            field=models.CharField(
                choices=[
                    ("HOURLY", "Hourly"),
                    ("BIHOURLY", "Bihourly"),
                    ("EVERY_MORNING", "Every Morning"),
                    ("DAILY_AT_NOON", "Daily at Noon"),
                    ("EVERY_EVENING", "Every Evening"),
                    ("ON_MONDAYS", "On Mondays"),
                    ("ON_THURSDAYS", "On Thursdays"),
                    ("ON_SATURDAYS", "On Saturdays"),
                    ("ON_SUNDAYS", "On Sundays"),
                    ("TWICE_A_WEEK", "Twice a week"),
                    ("FIRST_DAY_OF_THE_MONTH", "First Day of the Month"),
                    ("MIDDLE_OF_THE_MONTH", "Middle Day of the Month"),
                    ("END_OF_THE_MONTH", "End of the Month"),
                    ("THRICE_A_MONTH", "Thrice a month"),
                ],
                default="DAILY_AT_NOON",
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "refresh_delay__in",
                    [
                        "HOURLY",
                        "BIHOURLY",
                        "EVERY_MORNING",
                        "DAILY_AT_NOON",
                        "EVERY_EVENING",
                        "ON_MONDAYS",
                        "ON_THURSDAYS",
                        "ON_SATURDAYS",
                        "ON_SUNDAYS",
                        "TWICE_A_WEEK",
                        "FIRST_DAY_OF_THE_MONTH",
                        "MIDDLE_OF_THE_MONTH",
                        "END_OF_THE_MONTH",
                        "THRICE_A_MONTH",
                    ],
                )),
                name="feeds_feed_refresh_delay_type_valid",
            ),
        ),
    ]
