# Generated by Django 5.0.3 on 2024-03-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0010_alter_article_authors_alter_article_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readinglist",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="readinglist",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
