# Legadilo
# Copyright (C) 2023-2025 by Legadilo contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.2 on 2025-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0010_remove_feed_feeds_feed_refresh_delay_type_valid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feeddeletedarticle",
            name="feeds_feeddeletedarticle_delete_article_once_per_feed",
        ),
        migrations.RenameField(
            model_name="feed",
            old_name="open_original_link_by_default",
            new_name="open_original_url_by_default",
        ),
        migrations.RenameField(
            model_name="feeddeletedarticle",
            old_name="article_link",
            new_name="article_url",
        ),
        migrations.RenameField(
            model_name="feedupdate",
            old_name="ignored_article_links",
            new_name="ignored_article_urls",
        ),
        migrations.AddConstraint(
            model_name="feeddeletedarticle",
            constraint=models.UniqueConstraint(
                models.F("article_url"),
                models.F("feed"),
                name="feeds_feeddeletedarticle_delete_article_once_per_feed",
            ),
        ),
    ]
