# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2 on 2025-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0010_remove_feed_feeds_feed_refresh_delay_type_valid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feeddeletedarticle",
            name="feeds_feeddeletedarticle_delete_article_once_per_feed",
        ),
        migrations.RenameField(
            model_name="feed",
            old_name="open_original_link_by_default",
            new_name="open_original_url_by_default",
        ),
        migrations.RenameField(
            model_name="feeddeletedarticle",
            old_name="article_link",
            new_name="article_url",
        ),
        migrations.RenameField(
            model_name="feedupdate",
            old_name="ignored_article_links",
            new_name="ignored_article_urls",
        ),
        migrations.AddConstraint(
            model_name="feeddeletedarticle",
            constraint=models.UniqueConstraint(
                models.F("article_url"),
                models.F("feed"),
                name="feeds_feeddeletedarticle_delete_article_once_per_feed",
            ),
        ),
    ]
