# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.4 on 2025-07-27 09:18
import html

from django.db import migrations

from legadilo.core.utils.security import full_sanitize


def apply_cleaner_sanitization(apps, schema_editor):
    Feed = apps.get_model("feeds", "Feed")
    for feed in Feed.objects.all():
        feed.title = _clean_field(feed.title)
        feed.description = _clean_field(feed.description)
        feed.save(update_fields=["title", "description"])

    FeedCategory = apps.get_model("feeds", "FeedCategory")
    for feed_category in FeedCategory.objects.all():
        feed_category.title = _clean_field(feed_category.title)
        feed_category.save(update_fields=["title"])


def _clean_field(field_value):
    unescaped = html.unescape(field_value)
    return full_sanitize(unescaped)


class Migration(migrations.Migration):
    dependencies = [
        (
            "feeds",
            "0011_remove_feeddeletedarticle_feeds_feeddeletedarticle_delete_article_once_per_feed_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(apply_cleaner_sanitization, migrations.RunPython.noop),
    ]
