# Generated by Django 5.0.3 on 2024-03-26 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0011_alter_readinglist_options_readinglist_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="tags",
            new_name="feed_tags",
        ),
    ]
