# Generated by Django 5.0.3 on 2024-03-29 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0012_rename_tags_article_feed_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tagging_reason",
                    models.CharField(
                        choices=[("ADDED_MANUALLY", "Added manually"), ("FROM_FEED", "From feed")],
                        default="ADDED_MANUALLY",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_tags",
                        to="feeds.article",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_tags",
                        to="feeds.feed",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True)),
                (
                    "article_tags",
                    models.ManyToManyField(
                        related_name="tags", through="feeds.ArticleTag", to="feeds.article"
                    ),
                ),
                (
                    "feed_tags",
                    models.ManyToManyField(
                        related_name="tags", through="feeds.FeedTag", to="feeds.feed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedtag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="feeds", to="feeds.tag"
            ),
        ),
        migrations.AddField(
            model_name="articletag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="articles", to="feeds.tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                models.F("slug"), models.F("user_id"), name="feeds_tag_tag_slug_unique_for_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="articletag",
            constraint=models.CheckConstraint(
                check=models.Q(("tagging_reason__in", ["ADDED_MANUALLY", "FROM_FEED"])),
                name="feeds_articletag_tagging_reason_valid",
            ),
        ),
    ]
