# Generated by Django 5.0.3 on 2024-03-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0013_articletag_feedtag_tag_feedtag_tag_articletag_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="feed",
            name="disabled_reason",
            field=models.CharField(blank=True),
        ),
    ]
