# SPDX-FileCopyrightText: 2023-2025 Legadilo contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.4 on 2025-08-01 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0013_feedarticle_feed_article_id_feedarticle_last_seen_at_and_more"),
        ("reading", "0013_apply_cleaner_sanitization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedupdate",
            old_name="ignored_article_urls",
            new_name="ignored_article_ids",
        ),
        migrations.AlterField(
            model_name="feedarticle",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feed_articles",
                to="reading.article",
            ),
        ),
        migrations.DeleteModel(
            name="FeedDeletedArticle",
        ),
    ]
