# Generated by Django 5.0.3 on 2024-03-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0014_alter_feed_description_alter_feed_disabled_reason"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="articletag",
            name="feeds_articletag_tagging_reason_valid",
        ),
        migrations.AlterField(
            model_name="articletag",
            name="tagging_reason",
            field=models.CharField(
                choices=[
                    ("ADDED_MANUALLY", "Added manually"),
                    ("FROM_FEED", "From feed"),
                    ("DELETED", "Deleted"),
                ],
                default="ADDED_MANUALLY",
            ),
        ),
        migrations.AddConstraint(
            model_name="articletag",
            constraint=models.CheckConstraint(
                check=models.Q(("tagging_reason__in", ["ADDED_MANUALLY", "FROM_FEED", "DELETED"])),
                name="feeds_articletag_tagging_reason_valid",
            ),
        ),
    ]
