# Generated by Django 5.0.3 on 2024-03-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0015_remove_articletag_feeds_articletag_tagging_reason_valid_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="articletag",
            constraint=models.UniqueConstraint(
                models.F("article"),
                models.F("tag"),
                name="feeds_articletag_tagged_once_per_article",
            ),
        ),
    ]
