# Generated by Django 5.0.3 on 2024-04-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0018_feedtag_feeds_feedtag_tagged_once_per_feed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglisttag",
            name="filter_type",
            field=models.CharField(
                choices=[("INCLUDE", "Include"), ("EXCLUDE", "Exclude")], default="INCLUDE"
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglisttag",
            constraint=models.CheckConstraint(
                check=models.Q(("filter_type__in", ["INCLUDE", "EXCLUDE"])),
                name="feeds_readinglisttag_filter_type_valid",
            ),
        ),
    ]
