# Generated by Django 5.0.3 on 2024-04-04 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0019_readinglisttag_filter_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="exclude_tag_operator",
            field=models.CharField(
                choices=[("ALL", "All"), ("ANY", "Any")],
                default="ALL",
                help_text="Defines whether the articles must have all or any of the tags to be excluded from the reading list.",
            ),
        ),
        migrations.AddField(
            model_name="readinglist",
            name="include_tag_operator",
            field=models.CharField(
                choices=[("ALL", "All"), ("ANY", "Any")],
                default="ALL",
                help_text="Defines whether the articles must have all or any of the tags to be included in the reading list.",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                check=models.Q(("exclude_tag_operator__in", ["ALL", "ANY"])),
                name="feeds_readinglist_exclude_tag_operator_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                check=models.Q(("include_tag_operator__in", ["ALL", "ANY"])),
                name="feeds_readinglist_include_tag_operator_valid",
            ),
        ),
    ]
