# Generated by Django 5.0.3 on 2024-04-06 17:23

from django.db import migrations, models
from slugify import slugify


def create_slug_for_all_articles(apps, schema_editor):
    article_model = apps.get_model("feeds", "Article")

    for article in article_model.objects.all():
        article.slug = slugify(article.title)
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0020_readinglist_exclude_tag_operator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=255, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(create_slug_for_all_articles, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
