# Generated by Django 5.0.3 on 2024-04-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0021_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readinglist",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
