# Generated by Django 5.0.3 on 2024-04-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0022_alter_readinglist_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_for_later",
            field=models.BooleanField(default=False),
        ),
    ]
