# Generated by Django 5.0.3 on 2024-04-09 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0023_article_is_for_later"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="for_later_status",
            field=models.CharField(
                choices=[
                    ("ALL", "All"),
                    ("ONLY_FOR_LATER", "Only for later"),
                    ("ONLY_NOT_FOR_LATER", "Only for not later"),
                ],
                default="ALL",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                check=models.Q((
                    "for_later_status__in",
                    ["ALL", "ONLY_FOR_LATER", "ONLY_NOT_FOR_LATER"],
                )),
                name="feeds_readinglist_for_later_status_valid",
            ),
        ),
    ]
