# Generated by Django 5.0.4 on 2024-04-16 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0025_article_reading_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="articles_reading_time",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Include only articles that take more or less than this time to read.",
            ),
        ),
        migrations.AddField(
            model_name="readinglist",
            name="articles_reading_time_operator",
            field=models.CharField(
                choices=[
                    ("UNSET", "Unset"),
                    ("MORE_THAN", "More than than"),
                    ("LESS_THAN", "Less than than"),
                ],
                default="UNSET",
                help_text="Whether the reading must be more or less that the supplied value.",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                check=models.Q((
                    "articles_reading_time_operator__in",
                    ["UNSET", "MORE_THAN", "LESS_THAN"],
                )),
                name="feeds_readinglist_articles_reading_time_operator_valid",
            ),
        ),
    ]
