# Generated by Django 5.0.4 on 2024-04-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0027_readinglist_enable_reading_on_scroll"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="auto_refresh_interval",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Time in seconds after which to refresh reading lists automatically. It must be at least 5 minutes. Any values lower that that will disable the feature for this reading list.",
            ),
        ),
    ]
