# Generated by Django 5.0.4 on 2024-04-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0028_readinglist_auto_refresh_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="article",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="article",
            name="was_opened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="is_read",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Q(("read_at__isnull", False)),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="was_opened",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Q(("opened_at__isnull", False)),
                output_field=models.BooleanField(),
            ),
        ),
    ]
