# Generated by Django 5.0.4 on 2024-04-20 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0030_remove_article_created_at_remove_article_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedarticle",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_articles",
                to="feeds.article",
            ),
        ),
        migrations.AddField(
            model_name="feedarticle",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="feeds.feed",
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="feed_articles",
            field=models.ManyToManyField(
                related_name="feeds", through="feeds.FeedArticle", to="feeds.article"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="initial_source_title",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="initial_source_type",
            field=models.CharField(
                choices=[("FEED", "Feed"), ("MANUAL", "Manual")], default="FEED"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedarticle",
            constraint=models.UniqueConstraint(
                models.F("feed"),
                models.F("article"),
                name="feeds_feedarticle_article_linked_once_per_feed",
            ),
        ),
    ]
