# Generated by Django 5.0.4 on 2024-04-20 15:18

from django.db import migrations, models


def prefill_new_fields(apps, schema_editor):
    article_model = apps.get_model("feeds", "Article")
    for article in article_model.objects.select_related("feed", "feed__user"):
        article.user = article.feed.user
        article.initial_source_title = article.feed.title
        article.save()


def link_articles_to_feeds(apps, schema_editor):
    article_model = apps.get_model("feeds", "Article")
    feed_article_model = apps.get_model("feeds", "FeedArticle")

    for article in article_model.objects.all():
        feed_article_model.objects.update_or_create(
            feed=article.feed,
            article=article,
        )


def merge_duplicated_articles(apps, schema_editor):
    article_model = apps.get_model("feeds", "Article")
    user_model = apps.get_model("users", "User")
    feed_article_model = apps.get_model("feeds", "FeedArticle")

    for user in user_model.objects.all():
        duplicated_links = list(
            article_model.objects.values_list("link", flat=True)
            .alias(clinks=models.Count("link", filter=models.Q(user=user)))
            .filter(clinks__gt=1, user=user)
        )
        for duplicated_link in duplicated_links:
            articles_qs = article_model.objects.filter(link=duplicated_link).order_by("id")
            article_to_keep = articles_qs.first()
            articles_to_delete = list(articles_qs[1:])
            for article in articles_to_delete:
                if not article_to_keep.content:
                    article_to_keep.content = article.content

                feed_article_model.objects.update_or_create(
                    feed=article.feed,
                    article=article_to_keep,
                )

                article.delete()

            article_to_keep.save()


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0031_feedarticle_and_more"),
    ]

    operations = [
        migrations.RunPython(prefill_new_fields, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(link_articles_to_feeds, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(merge_duplicated_articles, reverse_code=migrations.RunPython.noop),
    ]
