# Generated by Django 5.0.4 on 2024-04-20 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0032_migrate_existing_articles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="article",
            name="feeds_article_article_unique_in_feed",
        ),
        migrations.RemoveField(
            model_name="article",
            name="feed",
        ),
        migrations.AlterField(
            model_name="article",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                models.F("user"), models.F("link"), name="feeds_article_article_unique_for_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("initial_source_type__in", ["FEED", "MANUAL"])),
                name="feeds_article_initial_source_type_valid",
            ),
        ),
    ]
