# Generated by Django 5.0.4 on 2024-04-21 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0034_remove_article_article_feed_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedarticle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedarticle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
