# Generated by Django 5.0.4 on 2024-04-21 13:15

from django.db import migrations, models

from legadilo.feeds import constants


def set_feed_update_status(apps, schema_editor):
    feed_update_model = apps.get_model("feeds", "FeedUpdate")
    feed_update_model.objects.filter(success=True).update(status=constants.FeedUpdateStatus.SUCCESS)
    feed_update_model.objects.filter(success=False).update(
        status=constants.FeedUpdateStatus.FAILURE
    )


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0035_feedarticle_created_at_feedarticle_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("NOT_MODIFIED", "Not Modified"),
                ],
                default="",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_feed_update_status, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="feedupdate",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["SUCCESS", "FAILURE", "NOT_MODIFIED"])),
                name="feeds_feedupdate_status_valid",
            ),
        ),
        migrations.RemoveField(
            model_name="feedupdate",
            name="success",
        ),
    ]
