# Generated by Django 5.0.4 on 2024-04-27 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0036_remove_feedupdate_success_feedupdate_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articletag",
            options={"ordering": ["article_id", "tag__name", "tag_id"]},
        ),
        migrations.AlterModelOptions(
            name="feedtag",
            options={"ordering": ["tag__name", "tag_id"]},
        ),
        migrations.AlterModelOptions(
            name="readinglisttag",
            options={"ordering": ["tag__name", "tag_id"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name", "id"]},
        ),
    ]
