# Generated by Django 5.0.4 on 2024-04-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0037_alter_articletag_options_alter_feedtag_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="preview_picture_alt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="preview_picture_url",
            field=models.URLField(blank=True),
        ),
    ]
