# Generated by Django 5.0.4 on 2024-04-28 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0038_article_preview_picture_alt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feed",
            name="feeds_feed_feed_type_valid",
        ),
        migrations.AlterField(
            model_name="feed",
            name="feed_type",
            field=models.CharField(
                choices=[
                    ("rss090", "RSS 0.90"),
                    ("rss091n", "RSS 0.91 (Netscape)"),
                    ("rss091u", "RSS 0.91 (Userland)"),
                    ("rss092", "RSS 0.92"),
                    ("rss093", "RSS 0.93"),
                    ("rss094", "RSS 0.94"),
                    ("rss20", "RSS 2.0"),
                    ("rss10", "RSS 1.0"),
                    ("rss", "RSS (unknown version)"),
                    ("atom01", "Atom 0.1"),
                    ("atom02", "Atom 0.2"),
                    ("atom03", "Atom 0.3"),
                    ("atom10", "Atom 1.0"),
                    ("atom", "Atom (unknown version)"),
                    ("cdf", "CDF"),
                    ("json1", "JSON 1"),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                check=models.Q((
                    "feed_type__in",
                    [
                        "rss090",
                        "rss091n",
                        "rss091u",
                        "rss092",
                        "rss093",
                        "rss094",
                        "rss20",
                        "rss10",
                        "rss",
                        "atom01",
                        "atom02",
                        "atom03",
                        "atom10",
                        "atom",
                        "cdf",
                        "json1",
                    ],
                )),
                name="feeds_feed_feed_type_valid",
            ),
        ),
    ]
