# Generated by Django 5.0.4 on 2024-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0039_remove_feed_feeds_feed_feed_type_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="external_article_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The id of the article in the its source.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="initial_source_title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="article",
            name="initial_source_type",
            field=models.CharField(
                choices=[("FEED", "Feed"), ("MANUAL", "Manual")], default="FEED", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="articletag",
            name="tagging_reason",
            field=models.CharField(
                choices=[
                    ("ADDED_MANUALLY", "Added manually"),
                    ("FROM_FEED", "From feed"),
                    ("DELETED", "Deleted"),
                ],
                default="ADDED_MANUALLY",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="disabled_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="feed",
            name="feed_type",
            field=models.CharField(
                choices=[
                    ("rss090", "RSS 0.90"),
                    ("rss091n", "RSS 0.91 (Netscape)"),
                    ("rss091u", "RSS 0.91 (Userland)"),
                    ("rss092", "RSS 0.92"),
                    ("rss093", "RSS 0.93"),
                    ("rss094", "RSS 0.94"),
                    ("rss20", "RSS 2.0"),
                    ("rss10", "RSS 1.0"),
                    ("rss", "RSS (unknown version)"),
                    ("atom01", "Atom 0.1"),
                    ("atom02", "Atom 0.2"),
                    ("atom03", "Atom 0.3"),
                    ("atom10", "Atom 1.0"),
                    ("atom", "Atom (unknown version)"),
                    ("cdf", "CDF"),
                    ("json1", "JSON 1"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="feedupdate",
            name="feed_etag",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="feedupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("NOT_MODIFIED", "Not Modified"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="readinglist",
            name="articles_max_age_unit",
            field=models.CharField(
                choices=[
                    ("UNSET", "Unset"),
                    ("HOURS", "Hour(s)"),
                    ("DAYS", "Day(s)"),
                    ("WEEKS", "Week(s)"),
                    ("MONTHS", "Month(s)"),
                ],
                default="UNSET",
                help_text="Define the unit for the previous number. Leave to unset to not use this feature.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="readinglist",
            name="articles_reading_time_operator",
            field=models.CharField(
                choices=[
                    ("UNSET", "Unset"),
                    ("MORE_THAN", "More than than"),
                    ("LESS_THAN", "Less than than"),
                ],
                default="UNSET",
                help_text="Whether the reading must be more or less that the supplied value.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="readinglist",
            name="exclude_tag_operator",
            field=models.CharField(
                choices=[("ALL", "All"), ("ANY", "Any")],
                default="ALL",
                help_text="Defines whether the articles must have all or any of the tags to be excluded from the reading list.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="readinglist",
            name="favorite_status",
            field=models.CharField(
                choices=[
                    ("ALL", "All"),
                    ("ONLY_FAVORITE", "Only favorite"),
                    ("ONLY_NON_FAVORITE", "Only non favorite"),
                ],
                default="ALL",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="readinglist",
            name="for_later_status",
            field=models.CharField(
                choices=[
                    ("ALL", "All"),
                    ("ONLY_FOR_LATER", "Only for later"),
                    ("ONLY_NOT_FOR_LATER", "Only for not later"),
                ],
                default="ALL",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="readinglist",
            name="include_tag_operator",
            field=models.CharField(
                choices=[("ALL", "All"), ("ANY", "Any")],
                default="ALL",
                help_text="Defines whether the articles must have all or any of the tags to be included in the reading list.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="readinglist",
            name="read_status",
            field=models.CharField(
                choices=[
                    ("ALL", "All"),
                    ("ONLY_UNREAD", "Only unread"),
                    ("ONLY_READ", "Only read"),
                ],
                default="ALL",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="readinglisttag",
            name="filter_type",
            field=models.CharField(
                choices=[("INCLUDE", "Include"), ("EXCLUDE", "Exclude")],
                default="INCLUDE",
                max_length=100,
            ),
        ),
    ]
