# Generated by Django 5.0.4 on 2024-05-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0040_alter_article_external_article_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="is_read",
        ),
        migrations.AddField(
            model_name="article",
            name="is_read",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(models.Q(("read_at__isnull", True)), then=False), default=True
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.RemoveField(
            model_name="article",
            name="was_opened",
        ),
        migrations.AddField(
            model_name="article",
            name="was_opened",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(models.Q(("opened_at__isnull", True)), then=False), default=True
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
