# Generated by Django 5.0.4 on 2024-05-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0041_alter_article_is_read_alter_article_was_opened"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="article_tags",
            new_name="articles",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="feed_tags",
            new_name="feeds",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="reading_list_tags",
            new_name="reading_lists",
        ),
        migrations.RenameField(
            model_name="feed",
            old_name="feed_articles",
            new_name="articles",
        ),
        migrations.AlterField(
            model_name="articletag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_tags",
                to="feeds.tag",
            ),
        ),
        migrations.AlterField(
            model_name="feedarticle",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_articles",
                to="feeds.feed",
            ),
        ),
        migrations.AlterField(
            model_name="feedtag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_tags",
                to="feeds.tag",
            ),
        ),
        migrations.AlterField(
            model_name="readinglisttag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_list_tags",
                to="feeds.tag",
            ),
        ),
    ]
