# Generated by Django 5.0.4 on 2024-05-02 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0042_rename_article_tags_tag_articles_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="feed",
            name="feeds_Feed_feed_url_unique",
        ),
        migrations.AddField(
            model_name="feedcategory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feeds",
                to="feeds.feedcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.UniqueConstraint(
                models.F("feed_url"), models.F("user"), name="feeds_feed_feed_url_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedcategory",
            constraint=models.UniqueConstraint(
                models.F("slug"), models.F("user"), name="feeds_feedcategory_unique"
            ),
        ),
    ]
