# Generated by Django 5.0.4 on 2024-05-02 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0043_feedcategory_remove_feed_feeds_feed_feed_url_unique_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedcategory",
            options={"ordering": ("name",)},
        ),
    ]
