# Generated by Django 5.0.6 on 2024-05-08 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0044_alter_feedcategory_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="refresh_delay",
            field=models.CharField(
                choices=[
                    ("HOURLY", "Hourly"),
                    ("BIHOURLY", "Bihourly"),
                    ("EVERY_MORNING", "Every Morning"),
                    ("DAILY_AT_NOON", "Daily at Noon"),
                    ("EVERY_EVENING", "Every Evening"),
                    ("ON_MONDAYS", "On Mondays"),
                    ("ON_THURSDAYS", "On Thursdays"),
                    ("TWICE_A_WEEK", "Twice a week"),
                    ("FIRST_DAY_OF_THE_MONTH", "First Day of the Month"),
                    ("MIDDLE_OF_THE_MONTH", "Middle Day of the Month"),
                    ("END_OF_THE_MONTH", "End of the Month"),
                    ("THRICE_A_MONTH", "Thrice a month"),
                ],
                default="DAILY_AT_NOON",
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                check=models.Q((
                    "refresh_delay__in",
                    [
                        "HOURLY",
                        "BIHOURLY",
                        "EVERY_MORNING",
                        "DAILY_AT_NOON",
                        "EVERY_EVENING",
                        "ON_MONDAYS",
                        "ON_THURSDAYS",
                        "TWICE_A_WEEK",
                        "FIRST_DAY_OF_THE_MONTH",
                        "MIDDLE_OF_THE_MONTH",
                        "END_OF_THE_MONTH",
                        "THRICE_A_MONTH",
                    ],
                )),
                name="feeds_feed_refresh_delay_type_valid",
            ),
        ),
    ]
