# Generated by Django 5.0.6 on 2024-05-08 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0045_feed_refresh_delay_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feed",
            options={"ordering": ("id",)},
        ),
    ]
